Temporary disable healthcheck

diff --git a/distribution/src/main/docker/websight-cms-luna/Dockerfile b/distribution/src/main/docker/websight-cms-luna/Dockerfile
--- a/distribution/src/main/docker/websight-cms-luna/Dockerfile
+++ b/distribution/src/main/docker/websight-cms-luna/Dockerfile
@@ -28,10 +28,10 @@ COPY src/main/docker/websight-cms-luna/bin /websight/bin
 COPY target/dependency/org.apache.sling.feature.launcher.jar /websight
 COPY target/artifacts/ /websight/cache/
 
-RUN apt-get update
-RUN apt-get -y install curl
+# RUN apt-get update
+# RUN apt-get -y install curl
 
-HEALTHCHECK --interval=15s --timeout=3s --start-period=5s CMD curl --fail http://localhost:8080/system/health || exit 1
+# HEALTHCHECK --interval=15s --timeout=3s --start-period=5s CMD curl --fail http://localhost:8080/system/health || exit 1
 
 WORKDIR /websight
 ENTRYPOINT [ "/websight/bin/launch.sh" ]
